package com.xunlei.analytics;

public final class g {
    public static int abc_action_bar_content_inset_material;
    public static int abc_action_bar_default_height_material;
    public static int abc_action_bar_default_padding_end_material;
    public static int abc_action_bar_default_padding_start_material;
    public static int abc_action_bar_icon_vertical_padding_material;
    public static int abc_action_bar_overflow_padding_end_material;
    public static int abc_action_bar_overflow_padding_start_material;
    public static int abc_action_bar_progress_bar_size;
    public static int abc_action_bar_stacked_max_height;
    public static int abc_action_bar_stacked_tab_max_width;
    public static int abc_action_bar_subtitle_bottom_margin_material;
    public static int abc_action_bar_subtitle_top_margin_material;
    public static int abc_action_button_min_height_material;
    public static int abc_action_button_min_width_material;
    public static int abc_action_button_min_width_overflow_material;
    public static int abc_alert_dialog_button_bar_height;
    public static int abc_button_inset_horizontal_material;
    public static int abc_button_inset_vertical_material;
    public static int abc_button_padding_horizontal_material;
    public static int abc_button_padding_vertical_material;
    public static int abc_config_prefDialogWidth;
    public static int abc_control_corner_material;
    public static int abc_control_inset_material;
    public static int abc_control_padding_material;
    public static int abc_dialog_fixed_height_major;
    public static int abc_dialog_fixed_height_minor;
    public static int abc_dialog_fixed_width_major;
    public static int abc_dialog_fixed_width_minor;
    public static int abc_dialog_list_padding_vertical_material;
    public static int abc_dialog_min_width_major;
    public static int abc_dialog_min_width_minor;
    public static int abc_dialog_padding_material;
    public static int abc_dialog_padding_top_material;
    public static int abc_disabled_alpha_material_dark;
    public static int abc_disabled_alpha_material_light;
    public static int abc_dropdownitem_icon_width;
    public static int abc_dropdownitem_text_padding_left;
    public static int abc_dropdownitem_text_padding_right;
    public static int abc_edit_text_inset_bottom_material;
    public static int abc_edit_text_inset_horizontal_material;
    public static int abc_edit_text_inset_top_material;
    public static int abc_floating_window_z;
    public static int abc_list_item_padding_horizontal_material;
    public static int abc_panel_menu_list_width;
    public static int abc_search_view_preferred_width;
    public static int abc_search_view_text_min_width;
    public static int abc_seekbar_track_background_height_material;
    public static int abc_seekbar_track_progress_height_material;
    public static int abc_select_dialog_padding_start_material;
    public static int abc_switch_padding;
    public static int abc_text_size_body_1_material;
    public static int abc_text_size_body_2_material;
    public static int abc_text_size_button_material;
    public static int abc_text_size_caption_material;
    public static int abc_text_size_display_1_material;
    public static int abc_text_size_display_2_material;
    public static int abc_text_size_display_3_material;
    public static int abc_text_size_display_4_material;
    public static int abc_text_size_headline_material;
    public static int abc_text_size_large_material;
    public static int abc_text_size_medium_material;
    public static int abc_text_size_menu_material;
    public static int abc_text_size_small_material;
    public static int abc_text_size_subhead_material;
    public static int abc_text_size_subtitle_material_toolbar;
    public static int abc_text_size_title_material;
    public static int abc_text_size_title_material_toolbar;
    public static int disabled_alpha_material_dark;
    public static int disabled_alpha_material_light;
    public static int highlight_alpha_material_colored;
    public static int highlight_alpha_material_dark;
    public static int highlight_alpha_material_light;
    public static int notification_large_icon_height;
    public static int notification_large_icon_width;
    public static int notification_subtext_size;

    static {
        abc_action_bar_content_inset_material = 2131165197;
        abc_action_bar_default_height_material = 2131165185;
        abc_action_bar_default_padding_end_material = 2131165198;
        abc_action_bar_default_padding_start_material = 2131165199;
        abc_action_bar_icon_vertical_padding_material = 2131165201;
        abc_action_bar_overflow_padding_end_material = 2131165202;
        abc_action_bar_overflow_padding_start_material = 2131165203;
        abc_action_bar_progress_bar_size = 2131165186;
        abc_action_bar_stacked_max_height = 2131165204;
        abc_action_bar_stacked_tab_max_width = 2131165205;
        abc_action_bar_subtitle_bottom_margin_material = 2131165206;
        abc_action_bar_subtitle_top_margin_material = 2131165207;
        abc_action_button_min_height_material = 2131165208;
        abc_action_button_min_width_material = 2131165209;
        abc_action_button_min_width_overflow_material = 2131165210;
        abc_alert_dialog_button_bar_height = 2131165184;
        abc_button_inset_horizontal_material = 2131165211;
        abc_button_inset_vertical_material = 2131165212;
        abc_button_padding_horizontal_material = 2131165213;
        abc_button_padding_vertical_material = 2131165214;
        abc_config_prefDialogWidth = 2131165189;
        abc_control_corner_material = 2131165215;
        abc_control_inset_material = 2131165216;
        abc_control_padding_material = 2131165217;
        abc_dialog_fixed_height_major = 2131165190;
        abc_dialog_fixed_height_minor = 2131165191;
        abc_dialog_fixed_width_major = 2131165192;
        abc_dialog_fixed_width_minor = 2131165193;
        abc_dialog_list_padding_vertical_material = 2131165218;
        abc_dialog_min_width_major = 2131165194;
        abc_dialog_min_width_minor = 2131165195;
        abc_dialog_padding_material = 2131165219;
        abc_dialog_padding_top_material = 2131165220;
        abc_disabled_alpha_material_dark = 2131165221;
        abc_disabled_alpha_material_light = 2131165222;
        abc_dropdownitem_icon_width = 2131165223;
        abc_dropdownitem_text_padding_left = 2131165224;
        abc_dropdownitem_text_padding_right = 2131165225;
        abc_edit_text_inset_bottom_material = 2131165226;
        abc_edit_text_inset_horizontal_material = 2131165227;
        abc_edit_text_inset_top_material = 2131165228;
        abc_floating_window_z = 2131165229;
        abc_list_item_padding_horizontal_material = 2131165230;
        abc_panel_menu_list_width = 2131165231;
        abc_search_view_preferred_width = 2131165232;
        abc_search_view_text_min_width = 2131165196;
        abc_seekbar_track_background_height_material = 2131165233;
        abc_seekbar_track_progress_height_material = 2131165234;
        abc_select_dialog_padding_start_material = 2131165235;
        abc_switch_padding = 2131165200;
        abc_text_size_body_1_material = 2131165236;
        abc_text_size_body_2_material = 2131165237;
        abc_text_size_button_material = 2131165238;
        abc_text_size_caption_material = 2131165239;
        abc_text_size_display_1_material = 2131165240;
        abc_text_size_display_2_material = 2131165241;
        abc_text_size_display_3_material = 2131165242;
        abc_text_size_display_4_material = 2131165243;
        abc_text_size_headline_material = 2131165244;
        abc_text_size_large_material = 2131165245;
        abc_text_size_medium_material = 2131165246;
        abc_text_size_menu_material = 2131165247;
        abc_text_size_small_material = 2131165248;
        abc_text_size_subhead_material = 2131165249;
        abc_text_size_subtitle_material_toolbar = 2131165187;
        abc_text_size_title_material = 2131165250;
        abc_text_size_title_material_toolbar = 2131165188;
        disabled_alpha_material_dark = 2131165251;
        disabled_alpha_material_light = 2131165252;
        highlight_alpha_material_colored = 2131165253;
        highlight_alpha_material_dark = 2131165254;
        highlight_alpha_material_light = 2131165255;
        notification_large_icon_height = 2131165256;
        notification_large_icon_width = 2131165257;
        notification_subtext_size = 2131165258;
    }
}
