package com.xunlei.analytics;

public final class k {
    public static int abc_action_bar_title_item;
    public static int abc_action_bar_up_container;
    public static int abc_action_bar_view_list_nav_layout;
    public static int abc_action_menu_item_layout;
    public static int abc_action_menu_layout;
    public static int abc_action_mode_bar;
    public static int abc_action_mode_close_item_material;
    public static int abc_activity_chooser_view;
    public static int abc_activity_chooser_view_list_item;
    public static int abc_alert_dialog_button_bar_material;
    public static int abc_alert_dialog_material;
    public static int abc_dialog_title_material;
    public static int abc_expanded_menu_layout;
    public static int abc_list_menu_item_checkbox;
    public static int abc_list_menu_item_icon;
    public static int abc_list_menu_item_layout;
    public static int abc_list_menu_item_radio;
    public static int abc_popup_menu_item_layout;
    public static int abc_screen_content_include;
    public static int abc_screen_simple;
    public static int abc_screen_simple_overlay_action_mode;
    public static int abc_screen_toolbar;
    public static int abc_search_dropdown_item_icons_2line;
    public static int abc_search_view;
    public static int abc_select_dialog_material;
    public static int notification_media_action;
    public static int notification_media_cancel_action;
    public static int notification_template_big_media;
    public static int notification_template_big_media_narrow;
    public static int notification_template_lines;
    public static int notification_template_media;
    public static int notification_template_part_chronometer;
    public static int notification_template_part_time;
    public static int select_dialog_item_material;
    public static int select_dialog_multichoice_material;
    public static int select_dialog_singlechoice_material;
    public static int support_simple_spinner_dropdown_item;

    static {
        abc_action_bar_title_item = 2130903040;
        abc_action_bar_up_container = 2130903041;
        abc_action_bar_view_list_nav_layout = 2130903042;
        abc_action_menu_item_layout = 2130903043;
        abc_action_menu_layout = 2130903044;
        abc_action_mode_bar = 2130903045;
        abc_action_mode_close_item_material = 2130903046;
        abc_activity_chooser_view = 2130903047;
        abc_activity_chooser_view_list_item = 2130903048;
        abc_alert_dialog_button_bar_material = 2130903049;
        abc_alert_dialog_material = 2130903050;
        abc_dialog_title_material = 2130903051;
        abc_expanded_menu_layout = 2130903052;
        abc_list_menu_item_checkbox = 2130903053;
        abc_list_menu_item_icon = 2130903054;
        abc_list_menu_item_layout = 2130903055;
        abc_list_menu_item_radio = 2130903056;
        abc_popup_menu_item_layout = 2130903057;
        abc_screen_content_include = 2130903058;
        abc_screen_simple = 2130903059;
        abc_screen_simple_overlay_action_mode = 2130903060;
        abc_screen_toolbar = 2130903061;
        abc_search_dropdown_item_icons_2line = 2130903062;
        abc_search_view = 2130903063;
        abc_select_dialog_material = 2130903064;
        notification_media_action = 2130903065;
        notification_media_cancel_action = 2130903066;
        notification_template_big_media = 2130903067;
        notification_template_big_media_narrow = 2130903068;
        notification_template_lines = 2130903069;
        notification_template_media = 2130903070;
        notification_template_part_chronometer = 2130903071;
        notification_template_part_time = 2130903072;
        select_dialog_item_material = 2130903073;
        select_dialog_multichoice_material = 2130903074;
        select_dialog_singlechoice_material = 2130903075;
        support_simple_spinner_dropdown_item = 2130903076;
    }
}
